#!/bin/bash
# Script 5: The Open Source Manifesto Generator
# Author: Shabi | Course: Open Source Software

echo "=========================================="
echo "      Welcome to the Manifesto Generator   "
echo "=========================================="
echo "Answer three questions to create your open source philosophy."
echo ""

# read -p displays a prompt to the user
read -p "1. Which open source tool is most important to you? (e.g., Python, Linux, VSCode): " TOOL
read -p "2. What is the most important freedom in open source? (e.g., Modify, Share, Study): " FREEDOM
read -p "3. Why do we need open source software in the future? (one sentence): " REASON

# date formatting: %d %B %Y = Day Full-Month Year
DATE=$(date '+%d %B %Y')
USER_NAME=$(whoami)
OUTPUT="manifesto_${USER_NAME}.txt"

# Creating the manifesto content
# > overwrites the file, >> appends to it
echo "------------------------------------------" > $OUTPUT
echo "      Open Source Manifesto - $DATE       " >> $OUTPUT
echo "------------------------------------------" >> $OUTPUT
echo "I, $USER_NAME, believe that $TOOL is essential for progress." >> $OUTPUT
echo "The freedom to $FREEDOM allows software to evolve beyond corporate limits." >> $OUTPUT
echo "In the future, open source matters because $REASON." >> $OUTPUT
echo "------------------------------------------" >> $OUTPUT
echo "Generated by Shabi's OSS Script." >> $OUTPUT

echo ""
echo "Manifesto saved to: $OUTPUT"
echo "Content of your manifesto:"
cat $OUTPUT
echo "=========================================="
